name: Tests

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Perform tests
        run: |
          sudo apt update && sudo apt-get -y install build-essential cmake wget clang
          cd dev
          ./test.sh
